const INFPCompatibilityMap: MBTICompatibilityMap = {
    INFP: 4,
    ENFP: 4,
    INFJ: 4,
    ENFJ: 5,
    INTJ: 4,
    ENTJ: 5,
    INTP: 4,
    ENTP: 4,
    ISFP: 1,
    ESFP: 1,
    ISTP: 1,
    ESTP: 1,
    ISFJ: 1,
    ESFJ: 1,
    ISTJ: 1,
    ESTJ: 1,
}

const ENFPCompatibilityMap: MBTICompatibilityMap = {
    INFP: 4,
    ENFP: 4,
    INFJ: 5,
    ENFJ: 4,
    INTJ: 5,
    ENTJ: 4,
    INTP: 4,
    ENTP: 4,
    ISFP: 1,
    ESFP: 1,
    ISTP: 1,
    ESTP: 1,
    ISFJ: 1,
    ESFJ: 1,
    ISTJ: 1,
    ESTJ: 1,
}

const INFJCompatibilityMap: MBTICompatibilityMap = {
    INFP: 4,
    ENFP: 5,
    INFJ: 4,
    ENFJ: 4,
    INTJ: 4,
    ENTJ: 4,
    INTP: 4,
    ENTP: 5,
    ISFP: 1,
    ESFP: 1,
    ISTP: 1,
    ESTP: 1,
    ISFJ: 1,
    ESFJ: 1,
    ISTJ: 1,
    ESTJ: 1,
}

const ENFJCompatibilityMap: MBTICompatibilityMap = {
    INFP: 5,
    ENFP: 4,
    INFJ: 4,
    ENFJ: 4,
    INTJ: 4,
    ENTJ: 4,
    INTP: 4,
    ENTP: 4,
    ISFP: 5,
    ESFP: 1,
    ISTP: 1,
    ESTP: 1,
    ISFJ: 1,
    ESFJ: 1,
    ISTJ: 1,
    ESTJ: 1,
}

const INTJCompatibilityMap: MBTICompatibilityMap = {
    INFP: 4,
    ENFP: 5,
    INFJ: 4,
    ENFJ: 4,
    INTJ: 4,
    ENTJ: 4,
    INTP: 4,
    ENTP: 5,
    ISFP: 3,
    ESFP: 3,
    ISTP: 3,
    ESTP: 3,
    ISFJ: 2,
    ESFJ: 2,
    ISTJ: 2,
    ESTJ: 2,
}

const ENTJCompatibilityMap: MBTICompatibilityMap = {
    INFP: 5,
    ENFP: 4,
    INFJ: 4,
    ENFJ: 4,
    INTJ: 4,
    ENTJ: 4,
    INTP: 5,
    ENTP: 4,
    ISFP: 3,
    ESFP: 3,
    ISTP: 3,
    ESTP: 3,
    ISFJ: 2,
    ESFJ: 2,
    ISTJ: 2,
    ESTJ: 2,
}

const INTPCompatibilityMap: MBTICompatibilityMap = {
    INFP: 4,
    ENFP: 4,
    INFJ: 4,
    ENFJ: 4,
    INTJ: 4,
    ENTJ: 5,
    INTP: 4,
    ENTP: 4,
    ISFP: 3,
    ESFP: 3,
    ISTP: 3,
    ESTP: 3,
    ISFJ: 2,
    ESFJ: 2,
    ISTJ: 2,
    ESTJ: 5,
}

const ENTPCompatibilityMap: MBTICompatibilityMap = {
    INFP: 4,
    ENFP: 4,
    INFJ: 5,
    ENFJ: 4,
    INTJ: 5,
    ENTJ: 4,
    INTP: 4,
    ENTP: 4,
    ISFP: 3,
    ESFP: 3,
    ISTP: 3,
    ESTP: 3,
    ISFJ: 2,
    ESFJ: 2,
    ISTJ: 2,
    ESTJ: 2,
}

const ISFPCompatibilityMap: MBTICompatibilityMap = {
    INFP: 1,
    ENFP: 1,
    INFJ: 1,
    ENFJ: 5,
    INTJ: 3,
    ENTJ: 3,
    INTP: 3,
    ENTP: 3,
    ISFP: 2,
    ESFP: 2,
    ISTP: 2,
    ESTP: 2,
    ISFJ: 3,
    ESFJ: 5,
    ISTJ: 3,
    ESTJ: 5,
}

const ESFPCompatibilityMap: MBTICompatibilityMap = {
    INFP: 1,
    ENFP: 1,
    INFJ: 1,
    ENFJ: 1,
    INTJ: 3,
    ENTJ: 3,
    INTP: 3,
    ENTP: 3,
    ISFP: 2,
    ESFP: 2,
    ISTP: 2,
    ESTP: 2,
    ISFJ: 5,
    ESFJ: 3,
    ISTJ: 5,
    ESTJ: 3,
}

const ISTPCompatibilityMap: MBTICompatibilityMap = {
    INFP: 1,
    ENFP: 1,
    INFJ: 1,
    ENFJ: 1,
    INTJ: 3,
    ENTJ: 3,
    INTP: 3,
    ENTP: 3,
    ISFP: 2,
    ESFP: 2,
    ISTP: 2,
    ESTP: 2,
    ISFJ: 3,
    ESFJ: 5,
    ISTJ: 3,
    ESTJ: 5,
}

const ESTPCompatibilityMap: MBTICompatibilityMap = {
    INFP: 1,
    ENFP: 1,
    INFJ: 1,
    ENFJ: 1,
    INTJ: 3,
    ENTJ: 3,
    INTP: 3,
    ENTP: 3,
    ISFP: 2,
    ESFP: 2,
    ISTP: 2,
    ESTP: 2,
    ISFJ: 5,
    ESFJ: 3,
    ISTJ: 3,
    ESTJ: 3,
}

const ISFJCompatibilityMap: MBTICompatibilityMap = {
    INFP: 1,
    ENFP: 1,
    INFJ: 1,
    ENFJ: 1,
    INTJ: 2,
    ENTJ: 3,
    INTP: 2,
    ENTP: 2,
    ISFP: 3,
    ESFP: 5,
    ISTP: 3,
    ESTP: 5,
    ISFJ: 4,
    ESFJ: 4,
    ISTJ: 4,
    ESTJ: 4,
}

const ESFJCompatibilityMap: MBTICompatibilityMap = {
    INFP: 1,
    ENFP: 1,
    INFJ: 1,
    ENFJ: 1,
    INTJ: 2,
    ENTJ: 3,
    INTP: 2,
    ENTP: 2,
    ISFP: 5,
    ESFP: 3,
    ISTP: 5,
    ESTP: 3,
    ISFJ: 4,
    ESFJ: 4,
    ISTJ: 4,
    ESTJ: 4,
}

const ISTJCompatibilityMap: MBTICompatibilityMap = {
    INFP: 1,
    ENFP: 1,
    INFJ: 1,
    ENFJ: 1,
    INTJ: 2,
    ENTJ: 3,
    INTP: 2,
    ENTP: 2,
    ISFP: 3,
    ESFP: 5,
    ISTP: 3,
    ESTP: 3,
    ISFJ: 4,
    ESFJ: 4,
    ISTJ: 4,
    ESTJ: 4,
}

const ESTJCompatibilityMap: MBTICompatibilityMap = {
    INFP: 1,
    ENFP: 1,
    INFJ: 1,
    ENFJ: 1,
    INTJ: 2,
    ENTJ: 3,
    INTP: 5,
    ENTP: 2,
    ISFP: 5,
    ESFP: 3,
    ISTP: 5,
    ESTP: 3,
    ISFJ: 4,
    ESFJ: 4,
    ISTJ: 4,
    ESTJ: 4,
}

export const MBTICompatibilityChart = {
    INFP: INFPCompatibilityMap,
    ENFP: ENFPCompatibilityMap,
    INFJ: INFJCompatibilityMap,
    ENFJ: ENFJCompatibilityMap,
    INTJ: INTJCompatibilityMap,
    ENTJ: ENTJCompatibilityMap,
    INTP: INTPCompatibilityMap,
    ENTP: ENTPCompatibilityMap,
    ISFP: ISFPCompatibilityMap,
    ESFP: ESFPCompatibilityMap,
    ISTP: ISTPCompatibilityMap,
    ESTP: ESTPCompatibilityMap,
    ISFJ: ISFJCompatibilityMap,
    ESFJ: ESFJCompatibilityMap,
    ISTJ: ISTJCompatibilityMap,
    ESTJ: ESTJCompatibilityMap,
}

type MBTICompatibilityMap = {
    INFP: number,
    ENFP: number,
    INFJ: number,
    ENFJ: number,
    INTJ: number,
    ENTJ: number,
    INTP: number,
    ENTP: number,
    ISFP: number,
    ESFP: number,
    ISTP: number,
    ESTP: number,
    ISFJ: number,
    ESFJ: number,
    ISTJ: number,
    ESTJ: number,
}
